version: '3'
services:
 server:
  build: ./backend/
  ports:
  - "8443:8443"
  - "8080:8080"
  env_file:
  - ./backend/startup.env
  volumes:
  - ./backend/certs/:/var/certs/:ro
  entrypoint: ./startup_server.sh
  depends_on:
  - redis

 redis:
  image: redis
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
  - ./backend/Redis/data/:/data
  - ./backend/Redis/log/:/data/log
  - ./backend/Redis/redis.conf:/usr/local/etc/redis/redis.conf

    # frontend:
         #     build: ./frontend/
     #     volumes:
             #      - ./frontend/src/:/usr/src/app
         #       - ./frontend/src//usr/src/app/node_modules
         #     ports:
             #       - '4200:80'
